// constants/flags for state change in redux store
export const USER_STATE_CHANGE = "USER_STATE_CHANGE"
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE"
export const USER_MEDICINES_STATE_CHANGE = 'USER_MEDICINES_STATE_CHANGE'
export const USER_ACTIVE_MEDICINES_STATE_CHANGE = 'USER_ACTIVE_MEDICINES_STATE_CHANGE'
export const USER_MOODS_STATE_CHANGE = 'USER_MOODS_STATE_CHANGE'
export const CLEAR_DATA = 'CLEAR_DATA'
export const USER_TODOLIST_STATE_CHANGE = 'USER_TODOLIST_STATE_CHANGE'
